# Generated by Django 4.2.11 on 2024-04-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование статуса')),
                ('priority', models.PositiveIntegerField(verbose_name='Приоритет статуса')),
                ('description', models.CharField(max_length=300, verbose_name='Описание статуса')),
                ('sign_of_relevance', models.BooleanField()),
                ('sign_of_decreased_attention', models.BooleanField()),
                ('sign_for_information', models.BooleanField()),
            ],
        ),
    ]
