# Generated by Django 5.0.3 on 2024-03-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('service_number', models.PositiveIntegerField(verbose_name='Табельный номер')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('org_admission_date', models.DateField(verbose_name='Дата приёма на работу в организацию')),
                ('division_admission_date', models.DateField(verbose_name='Дата приёма на работу в подразделение')),
                ('login', models.CharField(max_length=30, verbose_name='Логин')),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
