# Generated by Django 5.0.3 on 2024-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='position_titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование должности')),
                ('job_description_number', models.CharField(max_length=50, null=True, verbose_name='Номер должностной инструкции')),
            ],
            options={
                'verbose_name_plural': 'Наименования должностей',
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Сотрудники'},
        ),
    ]
