# Generated by Django 5.0.3 on 2024-03-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0002_position_titles_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position_titles',
            options={'ordering': ['name'], 'verbose_name_plural': 'Наименования должностей'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['surname'], 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.AddField(
            model_name='staff',
            name='position_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='org_structure.position_titles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position_titles',
            name='job_description_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Номер должностной инструкции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position_titles',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование должности'),
        ),
    ]
