# Generated by Django 5.0.3 on 2024-03-18 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0004_alter_position_titles_options_staff_dismissal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_structure.position_titles', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='org_level_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, verbose_name='Код структурной единицы 1 уровня (группы, лаборатории и т.д.)')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное наименование структурной единицв 1 уровня (группы, лаборатории и т.д.)')),
                ('staff', models.ManyToManyField(to='org_structure.staff', verbose_name='Состав')),
            ],
            options={
                'verbose_name_plural': 'Структурные единицы 1 уровня',
                'ordering': ['short_name'],
            },
        ),
    ]
