# Generated by Django 5.0.3 on 2024-03-18 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0005_alter_staff_position_title_org_level_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_level_1',
            name='head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='org_structure.position_titles', verbose_name='Начальник'),
            preserve_default=False,
        ),
    ]
