# Generated by Django 5.0.3 on 2024-03-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0006_org_level_1_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_level_1',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level1_head', to='org_structure.staff', verbose_name='Начальник'),
        ),
        migrations.AlterField(
            model_name='org_level_1',
            name='staff',
            field=models.ManyToManyField(related_name='level1_staff', to='org_structure.staff', verbose_name='Состав'),
        ),
    ]
