# Generated by Django 5.0.3 on 2024-03-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0007_alter_org_level_1_head_alter_org_level_1_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_level_1',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_structure.staff', verbose_name='Начальник'),
        ),
    ]
