# Generated by Django 5.0.3 on 2024-03-18 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0008_alter_org_level_1_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, verbose_name='Код структурной единицы')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное наименование структурной единицы')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_structure.staff', verbose_name='Начальник')),
                ('org_elements', models.ManyToManyField(related_name='subordinate_org_elements', to='org_structure.org_elements', verbose_name='Подчинённые организационные элементы')),
                ('staff', models.ManyToManyField(related_name='subordinate_staff', to='org_structure.staff', verbose_name='Непосредственные подчинённые')),
            ],
            options={
                'verbose_name_plural': 'Структурные единицы',
                'ordering': ['short_name'],
            },
        ),
        migrations.DeleteModel(
            name='org_level_1',
        ),
    ]
