# Generated by Django 5.0.3 on 2024-03-18 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0009_org_elements_delete_org_level_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_elements',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_structure.staff', verbose_name='Начальник'),
        ),
    ]
