# Generated by Django 5.0.3 on 2024-03-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0010_alter_org_elements_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_elements',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_structure.staff', verbose_name='Начальник'),
        ),
        migrations.AlterField(
            model_name='org_elements',
            name='org_elements',
            field=models.ManyToManyField(blank=True, null=True, related_name='subordinate_org_elements', to='org_structure.org_elements', verbose_name='Подчинённые организационные элементы'),
        ),
    ]
