# Generated by Django 5.0.3 on 2024-03-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0011_alter_org_elements_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_elements',
            name='org_elements',
            field=models.ManyToManyField(blank=True, related_name='subordinate_org_elements', to='org_structure.org_elements', verbose_name='Подчинённые организационные элементы'),
        ),
    ]
