# Generated by Django 5.0.3 on 2024-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0013_alter_org_elements_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], default='М', max_length=1, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
